project:
  type: website

website:
  title: "Rural Innovation Network data"
  search: false
  favicon: assets/images/Logo-Mark_CORI_Black.svg
  navbar:
    left:
      - href: index.qmd
        text: "Rural Innovation Network data"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: RIN-data-infrastructure.qmd
        text: RIN data infrastructure
      - section: "Cisco Network Academy (2024)"
        contents:
          - href: cisco/index.qmd
            text: Applicant & Learner progress
          - href: cisco/downloads.qmd
            text: Data downloads
          - href: cisco/eda-2025.qmd
            text: EDA for impact evaluation
      - section: "Grow With Google (2023 - 2024)"
        contents:
          - href: coursera/eda-2023-2024.qmd
            text: EDA for impact evaluation
      - section: "Grow With Google (2025)"
        contents:
          - href: coursera/index.qmd
            text: Applicant & Learner progress
          - href: coursera/eda-2025.qmd
            text: EDA for impact evaluation
format:
  html:
    theme:
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
  - "assets/*"
  - "downloads/*"

execute:
  cache: false
  freeze: false
