default:
  global: &global_params
    current_year: 2024
    monday_network_communities_url: https://ruralinnovation-group.monday.com/boards/6951894369
    monday_network_communities_tab_name: Current
    monday_network_communities_file_name: Network_Communities_Current_1746543710.xlsx
